version: '3.8'

services:
  server:
    build: ./server
    container_name: iris-api
    ports:
      - 8000:8000
  
  
  client:
    build: ./client
    container_name: iris-ui
    ports:
      - 8501:8501
    depends_on:
      - server